# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestTask' do
pod 'Kingfisher', '~> 5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestTask

end
